name: Fib-Test-and-Deploy
on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t noahapplegate/react-test -f ./client/Dockerfile.dev .
      - run: docker run -e CI=true noahapplegate/react-test npm test

  build-and-push-docker-image:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t noahapplegate/multi-client ./client
      - run: docker build -t noahapplegate/multi-nginx ./nginx
      - run: docker build -t noahapplegate/multi-server ./server
      - run: docker build -t noahapplegate/multi-worker ./worker

      - run: docker push noahapplegate/multi-client
      - run: docker push noahapplegate/multi-nginx
      - run: docker push noahapplegate/multi-server
      - run: docker push noahapplegate/multi-worker

  deploy-to-aws-eb:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Generate deployment package
        uses: actions/checkout@v2
      - run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: actions/checkout@v2
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-us-west-1-507649293101
          region: us-west-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
